language: python
git:
  depth: false
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
before_script:
  - git remote set-branches --add origin master-new
  - git fetch
# command to run tests
script:
  - python pylint-pre-hook.py
  - python -m unittest discover -v