language: python
git:
  depth: false
python:
  - "3.7"
# command to install dependencies
install:
  - sudo apt-get install -y swig3.0
  - pip install --upgrade pip
  - pip install .
# command to run tests
jobs:
  include:
    - stage: "Lint"
      name: "pylint"
      before_script: pip install pylint
      script: python pylint_pre_hook.py
    - stage: "Tests"
      name: "Unit tests"
      before_script:
        - pip install mock
        - pip install pytest
        - pip install pytest-cov
        - pip install coveralls
      script: PYTHONPATH=$(pwd) OMP_NUM_THREADS=1 pytest --cov=xfv/src/
      after_success: coveralls
    - name: "Integration tests"
      before_script:
        - sudo apt-get install -y hdf5-tools 
      script: python launch_integration_tests.py
stages:
  - Tests
  - Lint