language: python
git:
  depth: false
python:
  - "3.7"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install .
# command to run tests
jobs:
  include:
    - stage: "Lint"
      name: "pylint"
      before_script: pip install pylint
      script: python pylint_pre_hook.py
    - stage: "Tests"
      name: "Unit tests"
      before_script:
        - pip install mock
        - pip install pytest
        - pip install pytest-cov
        - pip install coveralls
      script: PYTHONPATH=$(pwd) pytest --cov=xfv/src/
      after_success: coveralls
stages:
  - Tests
  - Lint